language: node_js
node_js:
  - 7
sudo: required
services:
  - docker
install:
  - echo Hello docker!
script:
  - docker build . -t="macacajs/macaca-android-docker"
  - docker run -it --entrypoint="/bin/bash" macacajs/macaca-android-docker
